### PR TITLE
Updates to Laszip v3.4, layered compression

### PR DESCRIPTION
**Pull request by jason-daly**
Main addition is the set of 'LASreadItemCompressed_*_v3' types.

The interface to these types has changed to support the v3 compression algorithm and the use of a current context being passed between the decompression types. Concrete types were introduced to captured the decompressed records, in place of the use of byte arrays/buffers - see PointDataRecords.java. (this improves the readability of the code and places the code for unpacking the point data records in one place, rather than having to maintain it in several places).

A LasItemsFactory was introduced to better encapsulate the logic that creates the point record 'items'.

Includes some bug fixes, ported from the C++.

The 'extended' types and helper methods were dropped to reduce the amount of refactoring. I thought this was ok seeing as this code does not support _writing_ to las.

### CODE REVIEW

**Comment by mreutegg** [comment]
This is impressive work.

There are some new files you added. Can you please make sure they have the copyright header from the original sources? I assume you used https://github.com/LAStools/LAStools

**Comment by jason-daly** [comment]
Done.
I used your copyright for two of the files which are original code and were
not taken from the LasTools source. Is that ok?

**Comment by mreutegg** [comment]
> I used your copyright for two of the files which are original code and were not taken from the LasTools source. Is that ok?

That’s fine with me, but feel free to remove the copyright line if you want.

I noticed LasItemsFactory does not have a licence header. Can you please fix?

Otherwise this looks good.

**Comment by jason-daly** [comment]
Thanks. Done.

**Pull request merged**
